apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  selector:
    app: taskservice
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskservice
spec:
  selector:
    matchLabels:
      app: taskservice
  replicas: 1
  template:
    metadata:
      labels:
        app: taskservice
    spec:
      containers:
        - name: server
          image: kepburan/taskservice:latest
          ports:
            - name: http
              containerPort: 8082

---