apiVersion: v1
kind: Service
metadata:
  name: eventservice
spec:
  selector:
    app: eventservice
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice
spec:
  selector:
    matchLabels:
      app: eventservice
  replicas: 1
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
        - name: server
          image: kepburan/eventservice:latest
          ports:
            - name: http
              containerPort: 8081

---