apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: server
          image: kepburan/userservice:latest
          ports:
            - name: http
              containerPort: 8080

---